apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: krkn-perf-task
spec:
  params:
    - name: eaasSpaceSecretRef
      type: string
    - name: clusterName
      type: string                         
    - name: chaostest
      type: string
  volumes:
    - name: credentials
      emptyDir: {}
  steps:
    - name: get-kubeconfig
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/build-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
      params:
        - name: eaasSpaceSecretRef
          value: $(params.eaasSpaceSecretRef)
        - name: clusterName
          value: "$(params.clusterName)"
        - name: credentials
          value: credentials
    - name: app-test
      ref:
        resolver: git
        params:
          - name: url
            value: https://github.com/yogananth-subramanian/konflux-chaos.git
          - name: revision
            value: main
          - name: pathInRepo
            value: stepactions/step-deploy-krkn.yaml
      params:
        - name: KUBECONFIG
          value: "/credentials/$(steps.get-kubeconfig.results.kubeconfig)"
        - name: credentials
          value: credentials
        - name: chaostest
          value: $(params.chaostest)          